# Generated by Django 3.1.1 on 2021-03-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
