# Generated by Django 3.2.2 on 2021-12-20 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_doubtanswers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoubtAnswers',
            new_name='DoubtAnswer',
        ),
    ]
