# Generated by Django 3.2.2 on 2021-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_rename_doubtanswers_doubtanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtanswer',
            name='answer',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='doubtquestion',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
