# Generated by Django 3.2.2 on 2021-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
