# Generated by Django 3.2.2 on 2021-12-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_usercourse_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=70)),
            ],
        ),
    ]
