# Generated by Django 3.2.2 on 2021-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_coursestatus_course_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestatus',
            name='course_owner',
            field=models.CharField(max_length=50),
        ),
    ]
