# Generated by Django 3.2.2 on 2021-12-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_coursestatus_course_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseStatus',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='active',
            new_name='is_active',
        ),
    ]
