# Generated by Django 3.2.2 on 2021-12-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20211224_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=60)),
                ('roll_no', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('organization', models.CharField(max_length=100)),
            ],
        ),
    ]
