# Generated by Django 3.2.2 on 2021-12-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_coursestate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseState',
            new_name='CourseRequest',
        ),
    ]
