# Generated by Django 3.2.2 on 2021-12-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_rename_coursestate_courserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='user_course',
            field=models.CharField(default=' ', max_length=60),
        ),
    ]
