# Generated by Django 3.2.2 on 2021-12-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_courserequest_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequest',
            name='user_course',
        ),
    ]
